[package]
name = "mayland-config"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
readme = "readme.md"

[dependencies]
annotate-snippets = "0.11.5"
bitflags = "2.9.4"
dirs = { workspace = true }
indexmap = "2.11.4"
mayfig = { git = "https://github.com/m4rch3n1ng/mayfig" }
mayland-comm = { workspace = true }
owo-colors = "4.2.2"
regex = "1.11.2"
regex-syntax = "0.8.6"
serde = { workspace = true, features = ["derive"] }
smithay = { workspace = true, features = ["backend_libinput"] }
thiserror = "2.0.16"
tracing = "0.1.41"

[dev-dependencies]
pretty_assertions = "1.4.1"

[lints]
workspace = true
